#!/bin/sh
PROG="cicada"
DESC="Adaptor for the CICADA pipeline tools"
USAGE1="${PROG} init"
USAGE2="${PROG} register-image-metadata <image_metadata_file>"
USAGE3="${PROG} get-image-metadata <image_metadata_file>"
USAGE4="${PROG} request-deployment-approval <image_metadata_file>"
USAGE5="${PROG} register-deployment <image_metadata_file>"

CICADA_REPO=gwilliam-ucar-edu/CICADA

HELP_DESC="
This script is an adaptor for the CICADA CD implementation See
CDIMPL-README.md.

Cicada can handle both the pipeline management and image mapping
responsibilities required of a CircleCI CD implementor. It uses branches
in a special GitHub repo (called CICADA) and CircleCI branch-triggered
jobs to handle pipeline management, and it uses GitHub release objects
and their assets to handing image mapping.
"
SCRIPTDIR=`cd \`dirname $0\`; pwd`
. ${SCRIPTDIR}/citools-basics.rc || exit 1

PATH="${SCRIPTDIR}/cicada-bin:$PATH" export PATH

case command in
  init)
      cicada-client-init || exit 1 ;;

  register-image-metadata)
      cicada-image-register "$1" || exit 1 ;;

  get-image-metadata)
      cicada-image-get-metadata $1 || exit 1 ;;

  request-deployment-approval)
      cicada-request-approval || exit 1 ;;

  register-deployment)
      cicada-register-deployment || exit 1 ;;

  *)
    echo "${PROG}: unknown command: $1" >&2
    echo "${USAGE}" >&2
    exit 1 ;;
esac

exit 0