#!/bin/sh
PROG="circle-post"
DESC="Submit a POST request to the CircleCI API"
USAGE1="${PROG} path"

CIRCLECI_URL="${CIRCLECI_URL:-https://circleci.com/api/v1.1}"
HELP_DESC="
Submit a POST request to the CircleCI API v1.1. The body of the request is
read from standard input.

If the HTTP response status is not a 200 status, the entire response
header and body are written to standard error and 1 is returned. If the
HTTP response status is 200, the response header is discarded, the body is
written to standard output, and 0 is returned.

The \"path\" argument is the URL without the leading \"scheme\" and common
path components for the V1.1 API (e.g., \"/project/...\").
"
HELP_ENV="
CIRCLECI_URL
   The base URL that the command-line argument will be appended to.
   If not given, \"https://circleci.com/api/v1.1\" is used.

CIRCLE_TOKEN
   A CircleCI Personal API Token that will be used to authenticate.
"

SCRIPTDIR=`cd \`dirname $0\`; pwd`
. ${SCRIPTDIR}/citools-basics.rc || exit 1

case $1 in
    /*)
        URL_PATH="$@" ;;
    *)
        URL_PATH="/$@" ;;
esac

URL="${CIRCLECI_URL}${URL_PATH}?circle-token=${CIRCLE_TOKEN}"

payload=`cat`

vecho "Running curl -is -L -X POST -H \"Content-Type: application/json\" -H \"Accept: application/json\" --data-binary \"\${payload}\" \"${URL}\" || exit 1"

response=`curl -is -L -X POST \
     -H "Content-Type: application/json" \
     -H "Accept: application/json" \
     --data-binary "${payload}" \
     "${URL}"` || exit 1

statusline=`echo "${response}" | head -1`
case $statusline in
    *200*)
        # If the request succeeded, strip out the HTTP response header and
        # output the body
        echo "${response}" | sed -n '/^{/,$p' ;;
    *)
        echo "${PROG}: api post request failed" >&2
        cat ${response} >&2
        exit 1 ;;
esac

exit 0
