#!/bin/sh
PROG="circle-debug-dump"
DESC="Dump out environment variable, git info, etc. in a CircleCI job"
USAGE="${PROG} [-h|--help]"
case $1 in
  -h|--help)
    cat <<EOF
NAME
    $PROG - $DESC

SYNOPSIS
    $USAGE

DESCRIPTION
    This script just dumps to standard output various information that can be
    helpful when debugging a CircleCI job.
    
    All environment variables are displayed, but the values of variables that
    look like secure keys are shown as "----".
EOF
    exit 0 ;;
esac

for command in \
    "ls -la ." \
    "ls -la $HOME" \
    "git status" \
    "git rev-list HEAD" \
    "git tag --list" \
    "git tag --list --points-at $CIRCLE_SHA1"
do
    echo "${command}:"
    sh -c "${command}" 2>&1 | sed -e 's/^/    /'
done

echo "printenv:"
printenv | sed -e 's/^/    /' \
               -e 's/PASSWORD=.*/PASSWORD=----/' \
               -e 's/PRIVATE_KEY=.*/PRIVATE_KEY=----/' \
               -e 's/SECRET_ACCESS_KEY=.*/SECRET_ACCESS_KEY=----/' \
               -e 's/TOKEN=.*/TOKEN=----/' \
               -e 's/KEYS=.*/KEYS=----/' \

