#!/bin/sh
PROG="circle-install-tools"
DESC="Install miscellaneous tools for a CircleCI workflow"
USAGE1="${PROG} [bindir]"
USAGE2="${PROG} -h|--help"

BINDIR=/usr/local/bin
HELP_DESC="
Install miscellaneous tools that might be needed in CircleCI job steps.
The installation directory can be provided as a command-line argument
(default=$BINDIR).
"
SCRIPTDIR=`cd \`dirname $0\`; pwd`
. ${SCRIPTDIR}/citools-basics.rc || exit 1

if [ ":${CITOOLS_CIRCLE_ENV}" != ":true" ] ; then
    . "${INIT_RC}" || exit 1
fi
# Verify all needed environment variables are set
circle-env || exit 1

BINDIR="${LOCAL_BIN}"
if [ ":$1" != ":" ] ; then
    cd $1 || exit 1
    BINDIR=`pwd` 
fi

vecho "Installing jq..."
install-jq "${BINDIR}"

need_AWS=n
for envvar in AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN ; do
    eval val=\"\$$envvar\"
    if [ ":$val" != ":" ] ; then
        need_AWS=y
        break
    fi
done
if [ $need_AWS = y ] ; then
    vecho "Installing AWS cli..."
    install-aws-cli "${BINDIR}"
    cd /tmp
    curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
    unzip awscli-bundle.zip
    /tmp/awscli-bundle/install -i ${BINDIR}
fi

exit 0


