#!/bin/sh
PROG=circle-docker-login-init
DESC="Retrieve and cache a \"docker login\" command"
USAGE1="${PROG} remote_image_name"

HELP_DESC="
Log in to a docker registry and cache the login command.
"
HELP_ARGS="
remote_image_name
    The name of the remote image, with or without a tag or
    digest specification.
"
SCRIPTDIR=`cd \`dirname $0\`; pwd`
. ${SCRIPTDIR}/citools-basics.rc || exit 1

if [ ":$1" = ":" ] ; then
    echo "${PROG}: remote image name argument required" >&2
    exit 1
fi
if [ ":$INIT_RC" = ":" ] ; then
    echo "${PROG}: INIT_RC variable is not defined" >&2
    exit 1
fi

registry=`docker-get-login --show-type "$1"` || exit 1
if [ ":$registry" = "ecr" ] ; then
    variable=ECR_DOCKER_LOGIN
elif [ ":$registry" = "dockerhub" ] ; then
    variable=DOCKERHUB_DOCKER_LOGIN
fi
login=`docker-get-login "$1" 2>/dev/null`
if [ ":$login" != ":" ] ; then
    vecho "Appending to $INIT_RC: '${variable}=\"${login}\" export ${variable'"
    echo "${variable}=\"${login}\" export ${variable}" >>${INIT_RC}
fi
exit 0
