#!/bin/sh
PROG=citools-docgen
DESC="Generate documentation from --help output"
USAGE1="${PROG} [--bindir=dir] docdir"

REPO_DEFAULT="NCAR/citools"

HELP_DESC="
This script creates documentation pages in the GitHub citools wiki. It
creates man-like text documents by invoking each script with its --help
option, and a markdown index file with links to the text documents.

Other repos that use the same scripting conventions as citools can use
this script as well.
"
HELP_OPTS="
--bindir=dir
    If given, the top-level directory containing the scripts to document.
    If not given, the top-level directory in the repo is used. If a
    relative path is provided, it is assumed to relative to the top-level
    directiry in the repo.
"
HELP_ARGS="
docdir
    The output directory.
"
HELP_ENV="
REPO
    The owner/repo name of the target script repository. Default is
    \"${REPO_DEFAULT}\".
"
HELP_FILES="
index.md
    The index file name.

<scriptname>.txt
    The help file for a script.
"

SCRIPTDIR=`cd \`dirname $0\`; pwd`
. ${SCRIPTDIR}/citools-basics.rc || exit 1

REPO=${REPO:=${REPO_DEFAULT}} export REPO
REPONAME=`expr "${REPO}" : '[^/]*/\(.*\)$'`
WIKI_URL="https://github.com/${REPO}/wiki"

REPO_ROOT=`git rev-parse --show-toplevel` || exit 1
BINDIR="${REPO_ROOT}"
case $1 in
    --bindir=/*)
        BINDIR=`expr "$1" : '--scriptdir=\(.*\)'`
        shift ;;
    --bindir=*)
        RELDIR=`expr "$1" : '--scriptdir=\(.*\)'`
        BINDIR="${REPO_ROOT}/${RELDIR}"
        shift ;;
esac

DOCDIR="$1"
if [ ":$DOCDIR" = ":" ] ; then
    echo "${PROG}: directory argument required" >&2
    exit 1
fi
if [ ! -d "${DOCDIR}" ] ; then
    echo "${PROG}: $DOCDIR: not a directory" >&2
    exit 1
fi
DOCDIR=`cd "${DOCDIR}"; pwd`

TMPFILE="${DOCDIR}/.tmp"
INDEXFILE="${DOCDIR}/Home.md"

:>${INDEXFILE}.tmp

cd "${BINDIR}" || exit 1

trap "rm -rf ${TMPFILE} ${INDEXFILE}.tmp ; exit 1" 0 1 2 13 15

set -vx
find . -type f ! -name '*~' -perm -0005 -exec grep -l '^PROG=' {} \; \
| while read file ; do
    relpath=`expr "${file}" : '\./\(.*\)$'`
    base=`basename "${relpath}"`
    descline=`sed -n -e '/^DESC=/p' ${file}`
    DESC="?"
    eval ${descline}
    echo '```text' >${TMPFILE}
    ${file} --help >>${TMPFILE}
    echo '```' >>${TMPFILE}
    if [ -s "${TMPFILE}" ] ; then
        dir=`dirname "${DOCDIR}/${file}"`
        mkdir -p "${dir}"
        mv "${TMPFILE}" "${DOCDIR}/${file}.md"
        echo "- [${relpath}](${WIKI_URL}/${base}) - ${DESC}" >>${INDEXFILE}.tmp
    fi
done

cat >${INDEXFILE} <<EOF
Welcome to the ${REPONAME} wiki!

Many documents in the wiki are generated automatically when a change is
committed. These documents are simply snapshots of each script's `--help`
documentation.

EOF

sort ${INDEXFILE}.tmp >>${INDEXFILE}
rm -f ${INDEXFILE}.tmp

trap "" 0
exit 0



