#!/bin/sh
PROG=git-show-unversioned-commits
DESC="List commit hashes and message for recent commits"
USAGE1="${PROG} [--tag=<bracket_tag>]"

HELP_DESC="
This script shows the abbreviated commit hash and commit message subject for
every commit after the last semantic version tag.
"
HELP_OPTS="
--tag=<bracket_tag>
    Instead of showing all commits and their message subjects, just show
    commits in which the message subject contains a substring of the form
    \"[<bracket_tag> *]\", and instead of showing the whole message, just
    show what follows <bracket_tag> inside the square brackets.
"

SCRIPTDIR=`cd \`dirname $0\`; pwd`
. ${SCRIPTDIR}/citools-basics.rc || exit 1

tag=
case $1 in
    --tag=*)
        tag=`expr "$1" : '--tag=\(.*\)'` ;;
esac

tags=`git tag --list --merged HEAD` || exit 1
latest_semver=`echo "${tags}" | versions -c`

if [ ":${latest_semver}" = ":" ] ; then
    first_rev=`git rev-list HEAD | tail -1`
else
    first_rev=`git rev-list -n 1 ${latest_semver}`
fi
last_rev=`git rev-list HEAD | head -1`

if [ "${first_rev}" = "${last_rev}" ] ; then
   revspec=" -n 1 ${last_rev}"
else
   revspec="${first_rev}..${last_rev}"
fi
if [ ":${tag}" = ":" ] ; then
    filter=cat
else
    filter="sed -n -e 's/.*\\[${tag} *\([^\\]]*\).*/\\1/p'"
fi
git log --pretty=format:"%h %s" ${revspec} | ${filter}



