#!/bin/sh
PROG=github-list-tags
DESC="List all tag references for a GitHub repo"
USAGE1="${PROG} repo_owner/repo_name"

HELP_DESC="
This script lists all tag references for a GitHub repo.
"
HELP_ARGS="
repo_owner/repo_name
    The owner username and repo name, separated by "/".
"
HELP_ENV="
GH_TOKEN
    A GitHub Personal Access Token that allows read access to the target
    repo.
"
SCRIPTDIR=`cd \`dirname $0\`; pwd`
. ${SCRIPTDIR}/citools-basics.rc || exit 1

if [ ":$1" = ":" ] ; then
    echo "{$PROG}: repo_owner/repo_name argument is required" >&2
    exit 1
fi
REPO="$1"

resp=`github-get /repos/${REPO}/git/refs/tags` || exit 1
echo "${resp}" | jq -r '.[].ref' | sed -e 's:.*/tags/::'
exit 0
