#!/bin/sh
PROG="github-get"
DESC="Submit a GET request to the GitHub API"
USAGE1="${PROG} path"
USAGE2="${PROG} -h|--help"
SCRIPTDIR=$(cd `dirname $0`; pwd)
. ${SCRIPTDIR}/init-path.rc

GITHUB_URL="${GITHUB_URL:-https://api.github.com}"

case $1 in
    -h|--help)
      cat <<EOF
NAME
    $PROG - $DESC

SYNOPSIS
    $USAGE1
    $USAGE2

DESCRIPTION
    Submit a GET request to the GitHub API.

    If the HTTP response status is 404, a "Not found" message is emitted and 1
    is returned. If the HTTP response status is another non-200 status, the
    entire response header and body are written to standard error and 1 is
    returned. If the HTTP response status is 200, the response header is
    discarded, the body is written to standard output, and 0 is returned.

    The "path" argument is the URL without the leading "scheme" (e.g.,
    "/user/repos".

    If given a -h or --help argument, the script will print help text and quit.

ENVIRONMENT
    GITHUB_URL
       The base URL that the command-line argument will be appended to.
       If not given, "https://api.github.com" is used.

    GH_TOKEN
       A GitHub Personal API Token that will be used to authenticate.

EOF
          exit 0 ;;
    /*)
        URL_PATH="$@" ;;
    *)
        URL_PATH="/$@" ;;
esac
URL="${GITHUB_URL}${URL_PATH}"

response=`curl -is -L \
     -H "Accept: application/vnd.github.v3+json" \
     -H "Authorization: token ${GH_TOKEN}" \
     "${URL}"` || exit 1

statusline=`echo "${response}" | head -1`
case $statusline in
    *404*)
        # This must be a non-release tag.
        echo "${PROG}: Not found ($URL_PATH)" >&2
        exit 1 ;;
    *200*)
        # If the request succeeded, strip out the HTTP response header and
        # output the body
        echo "${response}" | sed -n '/^{/,$p' ;;
    *)
        echo "${PROG}: api GET request failed" >&2
        cat ${response} >&2
        exit 1 ;;
esac

exit 0
