#!/bin/sh
PROG="install-aws-cli"
DESC="Install the AWS CLI"
USAGE1="${PROG} [dest_dir]"

BINDIR=/usr/local/bin
HELP_DESC="
Install the AWS Command Line Interface. The installation directory can
be provided as a command-line argument (default=$BINDIR).
"
HELP_ARGS="
dest_dir
    If given, the directory in which to install the tools.
"
SCRIPTDIR=`cd \`dirname $0\`; pwd`
. ${SCRIPTDIR}/citools-basics.rc || exit 1

if [ ":$1" != ":" ] ; then
    cd $1 || exit 1
    BINDIR=`pwd` 
fi

TMPDIR=/tmp/aws$$
trap "rm -rf ${TMPDIR} ; exit 1" 0 1 2 13 15
mkdir -p "${TMPDIR}"

cd ${TMPDIR}
curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip" || exit 1
unzip awscli-bundle.zip || exit 1
${TMPDIR}/awscli-bundle/install -i ${BINDIR} || exit 1

rm -rf "${TMPDIR}"
trap "" 0

exit 0


