#!/bin/sh
PROG="install-jq"
DESC="Install jq"
USAGE1="${PROG} [--force] [dest_dir]"
JQ_VERSION='1.5'
BINDIR=/usr/local/bin

HELP_DESC="
Install jq version ${JQ_VERSION}. The installation directory can be
provided as a command-line argument (default=$BINDIR).
"
HELP_OPTS="
--force
    If given, the jq will be installed even if it appears to be
    installed already.
"
HELP_ARGS="
dest_dir
    If given, the directory in which to install the tools.
"
SCRIPTDIR=`cd \`dirname $0\`; pwd`
. ${SCRIPTDIR}/citools-basics.rc || exit 1

if [ ":$1" = ":--force" ] ; then
    shift
else
    check_jq=`type jq 2>/dev/null`
    if [ ":${check_jq}" != ":" ] ; then
        vecho "${check_jq}"
        exit 0
    fi
fi
vecho "Installing jq..."

if [ ":$1" != ":" ] ; then
    cd $1 || exit 1
    BINDIR=`pwd` 
fi

. setup-scratchdir.rc

wget --no-check-certificate https://raw.githubusercontent.com/stedolan/jq/master/sig/jq-release.key -O ${SCRATCHDIR}/jq-release.key
wget --no-check-certificate https://raw.githubusercontent.com/stedolan/jq/master/sig/v${JQ_VERSION}/jq-linux64.asc -O ${SCRATCHDIR}/jq-linux64.asc
wget --no-check-certificate https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64 -O ${SCRATCHDIR}/jq-linux64
gpg --homedir ${SCRATCHDIR} --import ${SCRATCHDIR}/jq-release.key
gpg --homedir ${SCRATCHDIR} --verify ${SCRATCHDIR}/jq-linux64.asc ${SCRATCHDIR}/jq-linux64
cp ${SCRATCHDIR}/jq-linux64 ${BINDIR}/jq
chmod +x ${BINDIR}/jq

exit 0
