#!/bin/sh
PROG="parse-semver"
DESC="Parse semantic version strings"
USAGE1="${PROG} [-n] [-p] [-m] [-i] version_str"

HELP_DESC="
This script parses a given supposed semantic version string and writes
one or more of the components to standard output. If the input string is
not a valid semantic version string, nothing is written and 1 is returned.
If it is a valid semantic version string, 0 is returned.

Note that a leading \"v\" or \"V\" in the input string is allowed, but
ignored.
"
HELP_OPTS="
-n
    Print the numeric component (major.minor.patch).

-p
    Print the prerelease component, with its leading \"-\".

-m
    Print the metadata component, with its leading \"+\".

-i
    Print the input string (if it is valid).

When more than one of the -n, -p, -m options are given, the components
are printed consecutively with no intervening spaces. For example,
\"-np\" would cause \"1.0.0-beta+build2\" to be transformed to
\"1.0.0-beta\".

If -i is given along with -n, -p, or -m, its value is always written
before the other components and separated from them by a space.
"

SCRIPTDIR=`cd \`dirname $0\`; pwd`
. ${SCRIPTDIR}/citools-basics.rc || exit 1

NUMERIC=n
PRERELEASE=n
METADATA=n
INVAL=n
SEMVER=
ENV=
while [ $# != 0 ] ; do
    arg="$1"
    shift
    case $arg in
      -??*)
          narg=`expr "$arg" : '\(-.\).*'`
          rest=`expr "$arg" : '-.\(.*\)'`
          set : "${narg}" "-${rest}" "$@"
          shift ;;
      -n)
        NUMERIC=y ;;
      -p)
        PRERELEASE=y ;;
      -m)
        METADATA=y ;;
      -i)
        INVAL=y ;;
      -*)
        echo "{$PROG}: unknown option: $1" >&2
        exit 1 ;;
      *)
        SEMVER="${arg}"
    esac
done

if [ ":$SEMVER" = ":" ] ; then
    echo "${PROG}: version string argument is required" >&2
    exit 1
fi

#
# This is a strict check of semantic version correctness, except we allow a
# leading "v" or "V"
#
echo "${SEMVER}" | egrep '^[vV]?[0-9]+\.[0-9]+\.[0-9]+(-[-1-9A-za-z][-0-9A-za-z]*(\.[-1-9A-za-z][-0-9A-za-z]*)*)?(\+[-0-9A-Za-z]+(\.[-0-9A-Za-z]+)*)?$' >/dev/null
rc=$?
if [ "$rc" != 0 ] ; then
    exit $rc
fi

OUTVAL=
if [ $NUMERIC = y ] ; then
    OUTVAL=`expr "${SEMVER}" : '[vV]*\([^-+]*\).*'`
fi
if [ $PRERELEASE = y ] ; then
    OUTVAL=${OUTVAL}`expr "${SEMVER}" : '[^-]*\(-[^+]*\).*'`
fi
if [ $METADATA = y ] ; then
    OUTVAL=${OUTVAL}`expr "${SEMVER}" : '[^+]*\(\+.*\)'`
fi
set :
if [ $INVAL = y ] ; then
    set "$@" "${SEMVER}"
fi
set "$@" ${OUTVAL}
shift
if [ $# != 0 ] ; then
    echo "$@"
fi

exit 0

