#!/bin/sh
PROG=
DESC=""
USAGE1="${PROG}"

HELP_DESC="
**DESCRIBE SCRIPT**
"
HELP_OPTS="
--myopt
    **DESCRIPT OPTION**
"
HELP_ARGS="
myarg
    **DESCRIPT NON_OPTION ARGUMENTS**
"
HELP_ENV="
MYENV
    **DESCRIBE ENVIRONMENT VARIABLES HERE**
"
HELP_FILES="
myfile
    **DESCRIBE FILES HERE**
"

SCRIPTDIR=`cd \`dirname $0\`; pwd`
. ${SCRIPTDIR}/citools-basics.rc || exit 1

# if you need a scratch directory, uncomment the following:
#. setup-scratchdir.rc
