#!/bin/sh
PROG="sw-manifest"
DESC="Print a list of installed software on a linux host"
USAGE1="${PROG} [from-base]"
USAGE2="${PROG} -h|--help"
BASE=

case $1 in
    -h|--help)
        cat <<EOF
NAME
    $PROG - $DESC

SYNOPSIS
    $USAGE

DESCRIPTION
    Print a list of installed software on a linux host, including the output
    of \"uname -mvr\", the distro version, and all packages reported by the
    package manager.

    The name of the base image should be passed in as a command-line argument.
EOF
        exit 0 ;;
    -*)
        echo "${PROG}: unknown option: $1" >&2
        exit 1 ;;

    '')
        : ;;
    *)
        BASE="$1" ;;
esac
grep '.*:/docker/.*' /proc/1/cgroup >/dev/null 2>&1
if [ $? != 0 ] ; then
    echo "$PROG: Must be run in a docker container" >&2
    exit 1
fi

cd /etc/ || exit 1

kernelrel=`uname -r`
kernelvers=`uname -v`
machine=`uname -m`

KNOWN_RELEASEFILES="
  alpine-release
  centos-release
  fedora-release
  oracle-release
  debian_version
"

RELEASE_FILE=
RELEASE=
for releasefile in ${KNOWN_RELEASEFILES} ; do
    if [ -f ${releasefile} ] ; then
        read RELEASE <${releasefile}
        RELEASE_FILE=${releasefile}
        break
    fi
done
if [ ":$RELEASE" = ":" ] ; then
    echo "$PROG: Cannot determine linux distribution type!" >&2
    exit 1
fi

if [ ":$BASE" != ":" ] ; then
    echo "FROM: $BASE"
fi

echo "KERNEL_RELEASE $kernelrel"
echo "KERNEL_VERSION $kernelvers"
echo "MACHINE $machine"

case $RELEASE_FILE in
    alpine-release)
        apk info -vv 2>&1 | sed -e 's/ - .*//' | sort | \
            grep -v 'WARNING: ' | while read pkgvers ; do
                pkg=`echo "$pkgvers" | sed 's/-[0-9].*//'`
                vers=`echo "$pkgvers" | sed "s/^${pkg}-\([0-9].*\)/\1/"`
                echo "$pkg $vers"
            done ;;
        
    centos-release|fedora-release|oracle-release)
        rpm -qa | sort | sed "s/^/$cmd: /" | while read rpm pkgvers ; do
            pkg=`echo "$pkgvers" | sed 's/-[0-9].*//'`
            vers=`echo "$pkgvers" | sed "s/^${pkg}-\([0-9].*\)/\1/"`
            echo "$pkg $vers"
        done ;;

    debian_version)
        dpkg-query -W | tr '\t' ' ' ;;

esac

exit 0
