#!/bin/sh
PROG=trigger-deployment
DESC="Trigger a deployment in CircleCI from a sweg-deployments CircleCI job"
USAGE="${PROG} [-h|--help]"
VERSION=0.0.2

case $1 in
  -h|--help)
    cat <<EOF
NAME
    $PROG - $DESC

SYNOPSIS
    $USAGE

DESCRIPTION
    This script is meant to be run in a CircleCI job that is triggered when an
    image metadata file is uploaded to a branch in the "sweg-deployments"
    github repo.
EOF
    exit 0 ;;
esac

case ${CIRCLE_BRANCH} in
    '')
      echo "${PROG}: Not running from a CircleCI job" >&2
      exit 1 ;;
    master)
      echo "${PROG}: Nothing to be done on master branch" >&2
      exit 0 ;;
    *-test)
      TARGET_ENV=test
      SEMVER_SUFFIX=-test
      TARGET_REPO=`expr "${CIRCLE_BRANCH}" : '\(.*\)-test$'` ;;
    *-staging)
      TARGET_ENV=staging
      SEMVER_SUFFIX=-staging
      TARGET_REPO=`expr "${CIRCLE_BRANCH}" : '\(.*\)-staging$'` ;;
    *-production)
      TARGET_ENV=production
      SEMVER_SUFFIX=
      TARGET_REPO=`expr "${CIRCLE_BRANCH}" : '\(.*\)-production$'` ;;
    *)
      echo "${PROG}: Unsupported branch name: ${CIRCLE_BRANCH}" >&2
      exit 0 ;;
esac
echo VERSION=$VERSION
echo TARGET_ENV=$TARGET_ENV
echo TARGET_REPO=$TARGET_REPO

# Find the most recent updated file that looks like an image metadata file
git rev-list HEAD | while read release ; do
    filename=`git diff-tree --no-commit-id --name-only -r "${release}"`
    imagename=`expr "${filename}" : '\([0-9][0-9]*.[0-9][0-9]*.[0-9][0-9]*-[0-9.]*Z\).*'`
    if [ ":${imagename}" != ":" ] ; then
        echo "${imagename}"
        break
    fi
done >/tmp/imagename
read IMAGENAME </tmp/imagename
echo IMAGENAME=$IMAGENAME
RELEASE_TAG=`expr "${IMAGENAME}" : '\([0-9.]*\)-.*'`
echo RELEASE_TAG=$RELEASE_TAG

#
# Add log entry for deployment authorization
# If release tag does not exist
#  create it - this will trigger build
# else
#  trigger job
# 


