#!/bin/sh
#!/bin/sh
PROG=truthy
DESC="Return 1 if the string looks false, 0 otherwise"
USAGE1="${PROG} [--not] <strvalue>"

HELP_DESC="
If the string is "false", "no", a leading substring of either, regardless
of case, or if it is empty, return 1 (Bourne shell's concept of false).
Otherwise, return 0.
"
HELP_ARGS="
--not
    Reverse the sense fo the result.
"

SCRIPTDIR=`cd \`dirname $0\`; pwd`
. ${SCRIPTDIR}/citools-basics.rc || exit 1

rc=0
notrc=1
if [ ":$1" = ":--not" ] ; then
    shift
    rc=1
    notrc=0
fi
case $1 in
    [fF]|[fF][aA]|[fF][aA][lL]|[fF][aA][lL][sS]|[fF][aA][lL][sS][eE])
        exit ${notrc} ;;
    [nN]|[nN][oO])
        exit ${notrc} ;;
    '')
        exit ${notrc} ;;
    0)
        exit ${notrc} ;;
esac
exit ${rc}
