defaults: &defaults
  docker:
    - image: circleci/php:7-cli

version: 2.1

jobs:

  build:
    <<: *defaults

    steps:
      - checkout
      - run:
          name: "Gather Debug Info"
          command: |
            echo "whoami: `whoami`"
            echo PWD=`pwd`
            echo HOME="$HOME"
            echo "ls -la .:"
            ls -la .
            echo "ls -la $HOME:"
            ls -la $HOME
            echo printenv:
            printenv | sed -e 's/_PASSWORD=.*/_PASSWORD=----/' \
                           -e 's/_PASS=.*/_PASS=----/' \
                           -e 's/_KEY=.*/_KEY=----/' \
                           -e 's/_TOKEN=.*/_TOKEN=----/'
            echo git status:
            git status
            echo git rev-list HEAD
            git rev-list HEAD
            echo git tag --list
            git tag --list
            echo git tag --list --points-at \$CIRCLE_SHA1
            git tag --list --points-at $CIRCLE_SHA1
            IFS="$IFS:" ; export IFS
            set x $PATH ; shift
            for dir in "$@" ; do
                echo "$dir:"
                ls -l $dir | sed -e 's/^/  /'
            done
      - run:
          name: "Install CircleCI CLI"
          command: |
            set +e -vx
            curl -fSl https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh) | sed -e 1d -e 's:DEST=.*:DEST=$HOME/circleci:' >$HOME/install-cli.sh
            echo install-cli.sh:
            sed -e 's/^/  /' $HOME/install-cli.sh
            bash $HOME/install-cli.sh
            PATH=$HOME:$PATH export PATH
            circleci update check
            true

  publish:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: "Publish"
          command: |
            echo Publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/


