---
defaults: &defaults
  docker:
    - image: circleci/buildpack-deps:latest

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}

      - checkout

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - run:
          name: "Show Environment"
          command: |
              printenv
              git rev-list HEAD
              git tag --list


workflows:
  version: 2
  build-push:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+([-+].*)?$/

#      - push:
#          context: sweg
#          requires:
#            - build
#          filters:
#            tags:
#              only: /^\d+\.\d+\.\d+([-+].*)?$/

