version: 2.1

jobs:
  say-hello:
    docker:
      - image: circleci/php:7.2-cli

    steps:
      - run:
          name: "Say Hello"
          command: |
            echo Hello!

  say-howdy:
    docker:
      - image: circleci/php:7.2-cli

    steps:
      - run:
          name: "Say Howdy"
          command: |
            echo Howdy!

  build-push:
    docker:
      - image: circleci/php:7.2-cli

    steps:
      - checkout

      - run:
          name: "Gather Debug Info"
          command: |
            echo PWD=`pwd`
            echo HOME="$HOME"
            echo "ls -la .:"
            ls -la .
            echo "ls -la $HOME:"
            ls -la $HOME
            echo printenv:
            printenv | sed -e 's/PASSWORD=.*/PASSWORD=----/' \
                           -e 's/PRIVATE_KEY=.*/PRIVATE_KEY=----/' \
                           -e 's/SECRET_ACCESS_KEY=.*/SECRET_ACCESS_KEY=----/' \
                           -e 's/GH_TOKEN=.*/GH_TOKEN=----/'
            echo git status:
            git status
            echo git rev-list HEAD
            git rev-list HEAD
            echo git tag --list
            git tag --list
            echo git tag --list --points-at \$CIRCLE_SHA1
            git tag --list --points-at $CIRCLE_SHA1

workflows:
  build-push:
    jobs:
      - say-hello
      - say-howdy
      - build-push:
          filters:
            branches:
              only:
                - master
            tags:
              only: /.*/

