#!/bin/sh
PROG=cicada-log-deployment
DESC="Log a successful deployment to CICADA"
USAGE1="${PROG}"

HELP_DESC="
CICADA logs approvals to log files in the master branch of the CICADA
repo.
"
SCRIPTDIR=`cd \`dirname $0\`; pwd`
SCRIPTPARENT=`dirname ${SCRIPTDIR}`
. ${SCRIPTPARENT}/citools-basics.rc || exit 1
PATH="${SCRIPTPARENT}:${SCRIPTDIR}:$PATH" export PATH

cicada-client-init --check || exit 1

IMAGE_TAG=`cicada-image-get-metadata IMAGE_TAG`
cicada-log-write \
           --project=${CIRCLE_PROJECT_REPONAME} \
           --deploy-env=${DEPLOY_ENV} \
           --type=deployed \
           --image-tag="${IMAGE_TAG}" || exit 1 ;;

exit 0




