#!/bin/sh
PROG=cicada-clone-branch
DESC="Do a shallow clone of the given CICADA branch"
USAGE1="${PROG} [--dir=<dir>] <branch>"

HELP_DESC="
This script will do a shallow (depth=1) clone of the indicated branch.
The clone will written to a subdirectory called <branch> under the
indicated directory.
"
HELP_OPTS="
--dir=<dir>
    The directory under which the clone subdirectory will be written. If
    not given, the environment variable CICADA_CLONE_DIR will be checked
    for a default.
"
HELP_ARGS="
branch
    The branch name.
"
HELP_ENV="
CICADA_CLONE_DIR
    Default parent directory of the clone directory.

 GH_TOKEN
     A GitHub Personal API Token for accessing the CICADA repo.
"
SCRIPTDIR=`cd \`dirname $0\`; pwd`
SCRIPTPARENT=`dirname ${SCRIPTDIR}`
. ${SCRIPTPARENT}/citools-basics.rc || exit 1
PATH="${SCRIPTPARENT}:${SCRIPTDIR}:$PATH" export PATH

. cicada-env.rc || exit 1

DIR="${CICADA_CLONE_DIR}"
case $1 in
    --dir=*)
        DIR=`expr "$1" : '--dir=\(.*\)$'`
        shift ;;
esac
BRANCH="$1"
if [ ":${DIR}" = ":" ] ; then
    echo "${PROG}: --dir is required" >&2
    exit 1
fi
if [ ":${BRANCH}" = ":" ] ; then
    echo "${PROG}: branch name is required" >&2
    exit 1
fi
if [ ":${GH_TOKEN}" = ":" ] ; then
    echo "${PROG}: the GH_TOKEN environment variable is not set" >&2
    exit 1
fi

mkdir -p "${DIR}" || exit 1

git clone --branch ${BRANCH} --depth 1 git@github.com:${CICADA_REPO}.git "${DIR}/${BRANCH}"
if [ $? != 0 ] ; then
    echo "${PROG}: unable to clone ${CICADA_REPO} branch=${branch}" >&2
    exit 1
fi
exit 0



