#!/bin/sh
PROG=FAILURE
if [ ":$1" = ":--help" ] ; then
    exit 0
fi
if [ ":$TMPDIR" = ":" ] ; then
   echo "ERROR: TMPDIR environment variable must be set" >&2
   exit 1
fi
. testutils.rc

cat $TESTNAME
echo FAIL
cat $REPORT

read count <$NFAILED
count=`expr $count + 1`
echo ${count} >$NFAILED

